apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-metrics-prometheus-adapter
  namespace: monitoring
  labels:
    app: prometheus-adapter
data:
  config.yaml: |
    rules:
    - seriesQuery: 'submitter_queue_message_count{namespace!="",pod!="",service="receipts-submitter-ms"}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod: 
            resource: pod
      name:
        matches: "^(.*)_count"
        as: "${1}_total"
      metricsQuery: 'topk(1,<<.Series>>{<<.LabelMatchers>>})'
    
