kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: receipts-submitter-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: receipts-submitter-ms
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 100
    - type: Resource
      resource:
         name: cpu
         target:
            type: Utilization
            averageUtilization: 1500
    - type: Pods
      pods:
        metric:
          name: submitter_queue_message_total
        target:
          type: AverageValue
          averageValue: 900
