apiVersion: v1
kind: Service
metadata:
  name: receipts-submitter-ms
  labels:
    app: receipts-submitter-ms
    version: 0.1.221722-3
spec:
  type: ClusterIP
  ports:
  - name: http-api
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: iks-stage-blue-wdc-receipts-submitter-ms
